# Generated by Django 5.0 on 2025-11-12 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoluntarioExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('participante', 'Participante'), ('canje', 'Canje')], max_length=20)),
                ('total_asistencias', models.IntegerField(default=0)),
                ('fecha_primera_asistencia', models.DateField(blank=True, null=True)),
                ('fecha_ultima_asistencia', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voluntario Externo',
                'verbose_name_plural': 'Voluntarios Externos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CicloAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('minimo_asistencias_emergencias', models.IntegerField(default=0)),
                ('minimo_asistencias_asambleas', models.IntegerField(default=0)),
                ('minimo_asistencias_ejercicios', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ciclo de Asistencia',
                'verbose_name_plural': 'Ciclos de Asistencia',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='EventoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_evento', models.BigIntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('emergencia', 'Emergencia'), ('asamblea', 'Asamblea'), ('ejercicios', 'Ejercicios'), ('citaciones', 'Citaciones'), ('otras', 'Otras')], max_length=20)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('clave_emergencia', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('hora_emergencia', models.TimeField(blank=True, null=True)),
                ('tipo_asamblea', models.CharField(blank=True, choices=[('ordinaria', 'Ordinaria'), ('extraordinaria', 'Extraordinaria')], max_length=20, null=True)),
                ('tipo_ejercicio', models.CharField(blank=True, choices=[('compania', 'Compañía'), ('cuerpo', 'Cuerpo')], max_length=20, null=True)),
                ('nombre_citacion', models.CharField(blank=True, max_length=200, null=True)),
                ('motivo_otras', models.CharField(blank=True, max_length=200, null=True)),
                ('total_asistentes', models.IntegerField(default=0)),
                ('oficiales_comandancia', models.IntegerField(default=0)),
                ('oficiales_compania', models.IntegerField(default=0)),
                ('total_oficiales', models.IntegerField(default=0)),
                ('cargos_confianza', models.IntegerField(default=0)),
                ('voluntarios', models.IntegerField(default=0)),
                ('participantes', models.IntegerField(default=0)),
                ('canjes', models.IntegerField(default=0)),
                ('porcentaje_asistencia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Asistencia',
                'verbose_name_plural': 'Eventos de Asistencia',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('clave_bombero', models.CharField(blank=True, max_length=20, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_cargo', models.IntegerField(blank=True, null=True)),
                ('es_externo', models.BooleanField(default=False)),
                ('tipo_externo', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voluntario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_asistidos', to='voluntarios.voluntario')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistentes', to='voluntarios.eventoasistencia')),
                ('externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_asistidos', to='voluntarios.voluntarioexterno')),
            ],
            options={
                'verbose_name': 'Detalle de Asistencia',
                'verbose_name_plural': 'Detalles de Asistencia',
                'ordering': ['categoria', 'nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='RankingAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('nombre_completo', models.CharField(max_length=200)),
                ('clave_bombero', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.IntegerField(default=0)),
                ('emergencias', models.IntegerField(default=0)),
                ('asambleas', models.IntegerField(default=0)),
                ('ejercicios', models.IntegerField(default=0)),
                ('citaciones', models.IntegerField(default=0)),
                ('otras', models.IntegerField(default=0)),
                ('es_externo', models.BooleanField(default=False)),
                ('tipo_externo', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voluntario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranking_anual', to='voluntarios.voluntario')),
                ('externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranking_anual', to='voluntarios.voluntarioexterno')),
            ],
            options={
                'verbose_name': 'Ranking de Asistencia',
                'verbose_name_plural': 'Rankings de Asistencia',
                'ordering': ['-anio', '-total'],
                'unique_together': {('anio', 'externo'), ('anio', 'voluntario')},
            },
        ),
    ]
