# Generated by Django 5.0 on 2025-11-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0002_voluntarioexterno_cicloasistencia_eventoasistencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='clave_bombero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
