# Generated by Django 5.2 on 2025-11-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0003_alter_voluntario_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='compania_opcional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='desde',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='hasta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='nombre_primer_padrino',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='nombre_segundo_padrino',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='otros_cuerpos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
