# Generated by Django 5.2 on 2025-11-12 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0004_voluntario_compania_opcional_voluntario_desde_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reintegro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20)),
                ('fecha_reintegro', models.DateField()),
                ('motivo_reintegro', models.TextField()),
                ('oficio_numero', models.CharField(max_length=100)),
                ('fecha_oficio', models.DateField()),
                ('documento_reintegro', models.FileField(blank=True, null=True, upload_to='reintegros/')),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('tiempo_ausencia_dias', models.IntegerField(blank=True, null=True)),
                ('aprobado', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reintegros', to='voluntarios.voluntario')),
            ],
            options={
                'verbose_name': 'Reintegro',
                'verbose_name_plural': 'Reintegros',
                'ordering': ['-fecha_reintegro'],
            },
        ),
    ]
