# Generated by Django 5.2 on 2025-11-14 02:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0005_reintegro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='felicitacion',
            options={'ordering': ['-fecha_felicitacion'], 'verbose_name': 'Felicitación', 'verbose_name_plural': 'Felicitaciones'},
        ),
        migrations.RemoveField(
            model_name='felicitacion',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='felicitacion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='felicitacion',
            name='otorgado_por',
        ),
        migrations.AddField(
            model_name='felicitacion',
            name='autoridad_otorgante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='felicitacion',
            name='compania_otorgante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='felicitacion',
            name='documento_felicitacion',
            field=models.TextField(blank=True, help_text='Documento en base64', null=True),
        ),
        migrations.AddField(
            model_name='felicitacion',
            name='documento_nombre_original',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='felicitacion',
            name='fecha_felicitacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='felicitacion',
            name='fecha_oficio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='felicitacion',
            name='nombre_felicitacion',
            field=models.CharField(blank=True, help_text='Nombre específico cuando el tipo es "Otra"', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='felicitacion',
            name='oficio_numero',
            field=models.CharField(default='S/N', max_length=100),
        ),
        migrations.AddField(
            model_name='felicitacion',
            name='tipo_felicitacion',
            field=models.CharField(choices=[('destacado', 'Desempeño Destacado'), ('merito', 'Mérito Extraordinario'), ('valor', 'Acto de Valor'), ('servicio', 'Servicio Distinguido'), ('antiguedad', 'Reconocimiento por Antigüedad'), ('otra', 'Otra Felicitación')], default='destacado', max_length=20),
        ),
        migrations.AlterField(
            model_name='felicitacion',
            name='motivo',
            field=models.TextField(default='Sin especificar'),
        ),
    ]
