# Generated by Django 5.2 on 2025-11-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0006_alter_felicitacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoasistencia',
            name='suma_ranking',
            field=models.BooleanField(default=True, help_text='Si False, no cuenta para el ranking anual (ej: directorio)'),
        ),
        migrations.AlterField(
            model_name='eventoasistencia',
            name='tipo',
            field=models.CharField(choices=[('emergencia', 'Emergencia'), ('asamblea', 'Asamblea'), ('ejercicios', 'Ejercicios'), ('citaciones', 'Citaciones'), ('otras', 'Otras'), ('directorio', 'Directorio de Compañía')], max_length=20),
        ),
    ]
