# Generated by Django 5.2 on 2025-11-14 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0007_eventoasistencia_suma_ranking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoCompania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del logo (ej: Logo Oficial, Logo Aniversario)', max_length=100)),
                ('imagen', models.TextField(help_text='Imagen en formato Base64')),
                ('activo', models.BooleanField(default=False, help_text='Logo actualmente en uso')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción u ocasión de uso', null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('cargado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logo de Compañía',
                'verbose_name_plural': 'Logos de Compañía',
                'ordering': ['-activo', '-fecha_carga'],
            },
        ),
    ]
