# Generated by Django 5.2 on 2025-11-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0008_logocompania'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logocompania',
            options={'ordering': ['-fecha_carga'], 'verbose_name': 'Logo de Compañía', 'verbose_name_plural': 'Logos de Compañía'},
        ),
        migrations.RemoveField(
            model_name='logocompania',
            name='activo',
        ),
        migrations.AddField(
            model_name='logocompania',
            name='usar_en_asistencias',
            field=models.BooleanField(default=False, help_text='Usar en headers de asistencias'),
        ),
        migrations.AddField(
            model_name='logocompania',
            name='usar_en_pdfs',
            field=models.BooleanField(default=False, help_text='Usar en PDFs (fichas, certificados, etc.)'),
        ),
        migrations.AddField(
            model_name='logocompania',
            name='usar_en_sidebar',
            field=models.BooleanField(default=False, help_text='Usar en el sidebar del sistema'),
        ),
    ]
