# Generated by Django 5.2 on 2025-11-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0009_alter_logocompania_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoasistencia',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio'),
        ),
        migrations.AddField(
            model_name='eventoasistencia',
            name='hora_termino',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de término'),
        ),
    ]
