# Generated by Django 5.2 on 2025-11-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0010_eventoasistencia_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniforme',
            name='tipo',
            field=models.CharField(choices=[('estructural', 'Estructural'), ('forestal', 'Forestal'), ('rescate', 'Rescate'), ('hazmat', 'Hazmat'), ('tenidaCuartel', 'Tenida de Cuartel'), ('accesorios', 'Accesorios'), ('parada', 'Parada'), ('usar', 'USAR'), ('agreste', 'AGRESTE'), ('um6', 'UM-6'), ('gersa', 'GERSA')], max_length=20),
        ),
    ]
