# Generated by Django 5.2 on 2025-11-17 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0013_sistema_tesoreria_completo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagocuota',
            name='cuota',
        ),
        migrations.AddField(
            model_name='estadocuotasbombero',
            name='documento_estudiante',
            field=models.TextField(blank=True, help_text='Certificado de alumno regular en Base64', null=True),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='nombre',
            field=models.CharField(help_text='Nombre del evento/beneficio', max_length=200),
        ),
        migrations.CreateModel(
            name='CicloCuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('cerrado', models.BooleanField(default=False, help_text='Si está cerrado, no se pueden registrar más pagos')),
                ('precio_cuota_regular', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('precio_cuota_estudiante', models.DecimalField(decimal_places=2, default=3000, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, help_text='Fecha en que se cerró el ciclo', null=True)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos_cerrados', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ciclo de Cuotas',
                'verbose_name_plural': 'Ciclos de Cuotas',
                'ordering': ['-anio'],
            },
        ),
    ]
