# Generated by Django 5.0 on 2026-03-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0014_ciclos_cuotas_y_documento_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='fecha_limite_rendicion',
            field=models.DateField(blank=True, help_text='Fecha límite para rendir tarjetas', null=True),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='tipo',
            field=models.CharField(blank=True, help_text='Tipo de beneficio', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beneficio',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
