# Generated by Django 5.0 on 2026-03-16 07:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0016_ciclo_beneficios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientofinanciero',
            name='metodo_pago',
            field=models.CharField(default='efectivo', help_text='efectivo | transferencia', max_length=20),
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: BancoEstado Corriente', max_length=100)),
                ('banco', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50)),
                ('tipo_cuenta', models.CharField(choices=[('corriente', 'Corriente'), ('ahorro', 'Ahorro'), ('vista', 'Vista')], default='corriente', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, help_text='Null = Caja/Efectivo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='voluntarios.cuentabancaria'),
        ),
        migrations.AddField(
            model_name='pagobeneficio',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, help_text='Null = Efectivo/Caja', null=True, on_delete=django.db.models.deletion.SET_NULL, to='voluntarios.cuentabancaria'),
        ),
        migrations.AddField(
            model_name='pagocuota',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, help_text='Null = Efectivo/Caja', null=True, on_delete=django.db.models.deletion.SET_NULL, to='voluntarios.cuentabancaria'),
        ),
        migrations.CreateModel(
            name='DepositoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('numero_comprobante', models.CharField(blank=True, max_length=100)),
                ('comprobante_base64', models.TextField(blank=True, help_text='Imagen/PDF en Base64', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depositos', to='voluntarios.cuentabancaria')),
            ],
            options={
                'verbose_name': 'Depósito de Caja',
                'verbose_name_plural': 'Depósitos de Caja',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
