# Generated by Django 5.0 on 2026-03-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0017_cuentas_bancarias'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagobeneficio',
            name='comprobante_base64',
            field=models.TextField(blank=True, help_text='Imagen/PDF del comprobante en Base64', null=True),
        ),
        migrations.AddField(
            model_name='pagocuota',
            name='comprobante_base64',
            field=models.TextField(blank=True, help_text='Imagen/PDF del comprobante en Base64', null=True),
        ),
    ]
