# Generated by Django 5.0 on 2026-03-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0018_comprobante_base64_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='rut_titular',
            field=models.CharField(blank=True, default='', help_text='Ej: 61.123.456-7', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='nombre',
            field=models.CharField(help_text='Ej: Cuerpo de Bomberos de Puerto Montt', max_length=150),
        ),
    ]
