# Generated by Django 5.0 on 2026-03-17 04:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0019_rut_titular_cuenta_bancaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='categoria',
            field=models.CharField(choices=[('cuota', 'Cuota Mensual'), ('beneficio', 'Beneficio'), ('rifa', 'Rifa'), ('rifa_retiro', 'Retiro Fondos Rifa'), ('donacion', 'Donación'), ('multa', 'Multa'), ('otro_ingreso', 'Otro Ingreso'), ('gasto_operacional', 'Gasto Operacional'), ('gasto_equipamiento', 'Gasto Equipamiento'), ('otro_egreso', 'Otro Egreso')], max_length=30),
        ),
        migrations.CreateModel(
            name='AsignacionRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talonarios_asignados', models.IntegerField()),
                ('numeros', models.TextField(blank=True, default='[]')),
                ('estado', models.CharField(choices=[('no_retirada', 'No Retirada'), ('retirada', 'Retirada'), ('pagada', 'Pagada'), ('liberada', 'Liberada')], default='no_retirada', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('historial_liberaciones', models.TextField(blank=True, null=True)),
                ('fecha_retiro', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rifas_asignadas', to='voluntarios.voluntario')),
            ],
        ),
        migrations.CreateModel(
            name='PagoRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(default='efectivo', max_length=20)),
                ('numero_comprobante', models.CharField(blank=True, max_length=100)),
                ('comprobante_base64', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='voluntarios.asignacionrifa')),
                ('cuenta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voluntarios.cuentabancaria')),
            ],
        ),
        migrations.AddField(
            model_name='movimientofinanciero',
            name='pago_rifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='voluntarios.pagorifa'),
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('precio_numero', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numeros_por_talonario', models.IntegerField()),
                ('talonarios_voluntarios', models.IntegerField(default=0)),
                ('talonarios_honorarios_cia', models.IntegerField(default=0)),
                ('talonarios_honorarios_cuerpo', models.IntegerField(default=0)),
                ('talonarios_insignes', models.IntegerField(default=0)),
                ('estado', models.CharField(default='activa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ciclo'],
            },
        ),
        migrations.AddField(
            model_name='asignacionrifa',
            name='rifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='voluntarios.rifa'),
        ),
    ]
