# Generated by Django 5.0 on 2026-06-03 06:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0020_sistema_rifas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalVoluntarioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('debe_cambiar_clave', models.BooleanField(default=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_profile', to=settings.AUTH_USER_MODEL)),
                ('voluntario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portal_profile', to='voluntarios.voluntario')),
            ],
            options={
                'verbose_name': 'Perfil Portal Voluntario',
                'verbose_name_plural': 'Perfiles Portal Voluntarios',
                'ordering': ['voluntario__apellido_paterno', 'voluntario__nombre'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudPagoPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('cuota', 'Cuota Social'), ('beneficio', 'Beneficio'), ('rifa', 'Rifa')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('observada', 'Observada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], default='pendiente', max_length=20)),
                ('cuota_mes', models.IntegerField(blank=True, null=True)),
                ('cuota_anio', models.IntegerField(blank=True, null=True)),
                ('tipo_pago_beneficio', models.CharField(choices=[('normal', 'Normal'), ('extra', 'Extra')], default='normal', max_length=10)),
                ('nombre_pago', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('numero_comprobante', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='portal/comprobantes/%Y/%m/')),
                ('feedback_tesorero', models.TextField(blank=True, null=True)),
                ('observada_hasta', models.DateTimeField(blank=True, null=True)),
                ('revisada_at', models.DateTimeField(blank=True, null=True)),
                ('aprobada_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignacion_beneficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_portal', to='voluntarios.asignacionbeneficio')),
                ('asignacion_rifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_portal', to='voluntarios.asignacionrifa')),
                ('cuenta_bancaria_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_portal', to='voluntarios.cuentabancaria')),
                ('pago_beneficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_portal', to='voluntarios.pagobeneficio')),
                ('pago_cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_portal', to='voluntarios.pagocuota')),
                ('pago_rifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_portal', to='voluntarios.pagorifa')),
                ('portal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_portal', to=settings.AUTH_USER_MODEL)),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_portal_revisadas', to=settings.AUTH_USER_MODEL)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_portal', to='voluntarios.voluntario')),
            ],
            options={
                'verbose_name': 'Solicitud de Pago Portal',
                'verbose_name_plural': 'Solicitudes de Pago Portal',
                'ordering': ['-created_at'],
            },
        ),
    ]
