# Generated by Django 5.0 on 2026-06-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0022_backfill_portal_voluntarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='fecha_ingreso_efectiva',
            field=models.DateField(blank=True, null=True),
        ),
    ]
