# Generated by Django 6.0.7 on 2026-07-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0023_voluntario_fecha_ingreso_efectiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, default='', max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(blank=True, default='', max_length=50)),
                ('marca', models.CharField(blank=True, default='', max_length=100)),
                ('tamano', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], default='', max_length=20)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=100)),
                ('responsable', models.CharField(blank=True, default='', max_length=150)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=150)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Item de Inventario',
                'verbose_name_plural': 'Items de Inventario',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
