# Generated by Django 6.0.7 on 2026-07-27 07:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0025_seed_inventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoSolicitudPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('observada', 'Observada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('numero_comprobante', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='portal/comprobantes_grupo/%Y/%m/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('feedback_tesorero', models.TextField(blank=True, null=True)),
                ('observada_hasta', models.DateTimeField(blank=True, null=True)),
                ('revisada_at', models.DateTimeField(blank=True, null=True)),
                ('aprobada_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta_bancaria_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_solicitud_portal', to='voluntarios.cuentabancaria')),
                ('portal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_solicitud_portal', to=settings.AUTH_USER_MODEL)),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_solicitud_revisados', to=settings.AUTH_USER_MODEL)),
                ('voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_solicitud_portal', to='voluntarios.voluntario')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='solicitudpagoportal',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='voluntarios.gruposolicitudpago'),
        ),
    ]
