# Generated by Django 6.0.7 on 2026-08-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0026_gruposolicitudpago_solicitudpagoportal_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoasistencia',
            name='numero_acta',
            field=models.CharField(blank=True, help_text='N° de acta (ej: 007/2026), usado para el Directorio', max_length=20, null=True),
        ),
    ]
