# Generated by Django 6.0.7 on 2026-08-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0027_eventoasistencia_numero_acta'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoasistencia',
            name='temas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de temas tratados: [{titulo, contenido}], usado para el Directorio'),
        ),
    ]
