# Generated by Django 6.0.7 on 2026-08-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0028_eventoasistencia_temas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sancion',
            name='tipo_sancion',
            field=models.CharField(choices=[('suspension', 'Suspensión'), ('renuncia', 'Renuncia'), ('separacion', 'Separación'), ('expulsion', 'Expulsión'), ('amonestacion_verbal', 'Amonestación Verbal'), ('amonestacion_escrita', 'Amonestación Escrita en su Hoja de Vida')], max_length=20),
        ),
    ]
