# Generated by Django 6.0.7 on 2026-08-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0029_alter_sancion_tipo_sancion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='tipo_cargo',
            field=models.CharField(choices=[('comandancia', 'Comandancia'), ('compania', 'Compañía'), ('consejo', 'Consejo de Compañía'), ('tecnico', 'Confianza'), ('departamento_comandancia', 'Departamento de Comandancia')], max_length=30),
        ),
    ]
