# Generated by Django 6.0.7 on 2026-08-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0030_alter_cargo_tipo_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='voluntario',
            name='fecha_aspirante',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='tipo_voluntario',
            field=models.CharField(choices=[('voluntario', 'Voluntario'), ('aspirante', 'Aspirante'), ('canje', 'Canje'), ('participante', 'Participante')], default='voluntario', max_length=20),
        ),
    ]
