# Generated by Django 6.0.7 on 2026-08-28 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0031_voluntario_fecha_aspirante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcuerdoOrgano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_organo', models.CharField(choices=[('asamblea', 'Asamblea'), ('directorio', 'Directorio')], max_length=20)),
                ('fecha_acuerdo', models.DateField()),
                ('tipo_sesion', models.CharField(choices=[('ordinaria', 'Ordinaria'), ('extraordinaria', 'Extraordinaria')], max_length=20)),
                ('glosa', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acuerdo de Asamblea/Directorio',
                'verbose_name_plural': 'Acuerdos de Asamblea/Directorio',
                'ordering': ['fecha_acuerdo', 'id'],
            },
        ),
    ]
