# Generated by Django 6.0.7 on 2026-08-29 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0032_acuerdoorgano'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuerdoorgano',
            name='evento',
            field=models.ForeignKey(blank=True, help_text='Asamblea o Directorio del que salió este acuerdo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acuerdos', to='voluntarios.eventoasistencia'),
        ),
    ]
