# Generated by Django 6.0.7 on 2026-09-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0033_acuerdoorgano_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoasistencia',
            name='fecha_aprobacion',
            field=models.DateField(blank=True, help_text='Fecha en que se aprobó el acta (se ingresa manualmente)', null=True),
        ),
    ]
