# Generated by Django 6.0.7 on 2026-09-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0034_eventoasistencia_fecha_aprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoasistencia',
            name='disculpados',
            field=models.JSONField(blank=True, default=list, help_text='Voluntarios que avisaron que no asistirían: [{id, nombre}]'),
        ),
    ]
